version: '3.8'

x-spring-app-common: &spring-app-common
  image: openjdk:21
  working_dir: /app
  volumes:
    - ./services/coupon/presentation/api/build/libs:/app
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/coupon?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SPRING_DATA_REDIS_HOST=redis
    - SPRING_DATA_REDIS_PORT=6379
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
  networks:
    - commerce-net

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: coupon
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - commerce-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6380:6379"
    networks:
      - commerce-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  spring-app-1:
    <<: *spring-app-common
    container_name: spring-app-1
    command: [ "java", "-jar", "api.jar", "--server.port=8081" ]

  spring-app-2:
    <<: *spring-app-common
    container_name: spring-app-2
    command: [ "java", "-jar", "api.jar", "--server.port=8082" ]

  spring-app-3:
    <<: *spring-app-common
    container_name: spring-app-3
    command: [ "java", "-jar", "api.jar", "--server.port=8083" ]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - spring-app-1
      - spring-app-2
      - spring-app-3
    networks:
      - commerce-net

volumes:
  db-data:
  redis-data:

networks:
  commerce-net:
    driver: bridge